### PR TITLE
Update FormPostResponse.js

### PR DESCRIPTION
**Pull request by danielcrisp**
Remove `querySelector` and use more widely supported method of submitting the form.

Fixes #779

### CODE REVIEW

**Comment by brockallen** [comment]
Once I get CLA confirmation from the .NET Foundation, I'll merge. Thx.

**Comment by brockallen** [comment]
Thanks.

**Comment by parkinsona** [comment]
Hi Guys,

Thanks for the fix for this, it was causing us issues for some of our users in IE.
Is this only in the dev branch?

Will this be added to the main build soon?

**Comment by brockallen** [comment]
RTM next week

**Comment by parkinsona** [comment]
That's great news @brockallen . I'm looking forward to implementing it. You've done well to get to RTM so soon.

**Pull request merged**
